<?php
$help_overview_text=<<<EOD

<p>
	<strong>Page scroll to id</strong> is a fully featured plugin for creating links that scroll the page smoothly to any id within the document.  
</p>

<p>
	The plugin replaces browser's "jumping" behavior with a smooth scrolling animation, when links with href value containing <code>#</code> are clicked. <br />
	It provides all the basic tools and advanced functionality for single-page websites, in-page navigation, back-to-top links etc. with features like: adjustable scrolling animation duration and easing, link and target highlighting via ready-to-use CSS classes, vertical and/or horizontal scrolling, scrolling from/to different pages etc. 
</p>

<p>If you like this plugin and find it useful, consider making a <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UYJ5G65M6ZA28" target="_blank">donation</a> :)</p>

EOD;
?>

<?php _e($help_overview_text, $this->plugin_slug); ?>