<?php
$help_sidebar_text=<<<EOD

<p><strong>For more information</strong></p>

<ul>
	<li><a href="http://manos.malihu.gr/page-scroll-to-id-for-wordpress/" target="_blank">Plugin homepage &amp; documentation</a></li>
	<li><a href="http://manos.malihu.gr/page-scroll-to-id-for-wordpress/2/" target="_blank">Knowledge Base – FAQ</a></li>
	<li><a href="http://manos.malihu.gr/page-scroll-to-id-for-wordpress-tutorial/" target="_blank">Basic tutorial</a></li>
</ul>

EOD;
?>

<?php _e($help_sidebar_text, $this->plugin_slug); ?>